### ISSUE TITLE
__metadata Causes FunctionClauseError

### ISSUE THREAD

**Issue by kitplummer** [doorgan/yarn_parser#1]
Trying to parse Jest's yarn.lock file and noticed this:

```
** (FunctionClauseError) no function clause matching in Npm.Yarnlockfile.extract_deps/1

     The following arguments were given to Npm.Yarnlockfile.extract_deps/1:
     
         # 1
         {:error, "expected newline while processing simple_block or block or comment or key_value or newline"}
```

Probably didn't figure you'd ever get feedback on this thing.  I believe you were actually helping a student of mine with a project she was working, since your YarnParser is in my project I'd seen some post in the Elixir Forum.  Much appreciated regardless.

Yarn 2 problems.

**Comment by kitplummer** [comment]
Here's the yarn.lock - https://github.com/facebook/jest/blob/master/yarn.lock#L4

**Comment by doorgan** [comment]
Thanks for your feedback! Indeed, I was helping someone when I wrote this library.

It seems yarn changed it's grammar in v2 and it now also has a PEGjs grammar file. I'll check it and try to update the parser to support the new yarn version in the next days.

**Comment by kitplummer** [comment]
Cool!  I'll stay tuned, much appreciation.

**Comment by doorgan** [comment]
It looks like yarn 2 moved to standard yaml files(it now uses `js-yaml` instead of a homemade custom parser), so it seems the best solution is to use YamlElixir for the those lockfiles
I pushed a version that automatically picks the correct parser with the same technique the original yarn parser uses(it's just a simple regex checking for the `# yarn lockfile v1` comment), I tested it with the lockfile you provided and a couple others and it seems to work fine

It's in the `fix/yarn_v2` branch, please check if it works correctly for your usecases:
`{:yarn_parser, git: "https://github.com/doorgan/yarn_parser.git", branch: "fix/yarn_v2"}`

It has some api changes too, now `YarnParser.decode` returns a `YarnLock` struct with a `:metadata` and `:dependencies` fields:
```elixir
iex> input =
...>   \"""
...>   # yarn lockfile v1
...>   prop1 val1
...>   block1:
...>     prop2 true
...>   prop3 123
...>   \"""
iex> YarnParser.decode(input)
{:ok, %YarnParser.YarnLock{
  dependencies: %{
    "prop1" => "val1",
    "block1" => %{
      "prop2" => true
    },
    "prop3" => 123
  },
  metadata: %{
    "version" => 1
  }
}}
```

Let me know how it works before I push it to master

**Comment by kitplummer** [comment]
Awesome!  Yep, that struct works great.  Thanks.

**Comment by doorgan** [comment]
Great! Changes were merged to master and published to hex
